### ISSUE TITLE
插件很好不过有个小建议

### ISSUE THREAD

**Issue by zhangchaolunha** [jenly1314/java-field-plugin#1]
我使用是java的代码..文档一般用到是在线的接口文档.常用的文档大部分其中会有很多多余的字段例如是否必填啊之类的..能不能智能识别或者做成可配置例如第几位作为类型第几位作为注解之类的,还有个就是文档大部分类型他不是java类型..是否可以自动转变,,比如string转String  number转Integer之类的呢

**Comment by jenly1314** [comment]
> 我使用是java的代码..文档一般用到是在线的接口文档.常用的文档大部分其中会有很多多余的字段例如是否必填啊之类的..能不能智能识别或者做成可配置例如第几位作为类型第几位作为注解之类的,还有个就是文档大部分类型他不是java类型..是否可以自动转变,,比如string转String number转Integer之类的呢

- 字段、字段类型、注释、所在列目前就支持可配置的，示例如下：
![image](https://user-images.githubusercontent.com/4995173/176574014-2046d518-9706-4c0b-9a98-5d0fdf253386.png)

- 文档上的字段类型定义非Java类型的话，目前没有支持转换，后续考虑加个配置来支持。（这个建议很好）

**Comment by jenly1314** [comment]
**JavaFieldGenerator** 新版本已发布：**支持字段类型转换配置** 

详情请参见：**README**
